server:
  port: 7000

spring:
  application:
    name: api-gateway

  # 🔥 CONFIGURACIÓN DE REDIS (RAILWAY)
  data:
    redis:
      url: redis://default:lGZOxJdQZZuXXCjUGMrnNgDQdApUEDnQ@tramway.proxy.rlwy.net:49800

  cloud:
    gateway:
      routes:
        # --- RUTAS DE NEGOCIO ---
        - id: weather-service
          uri: http://localhost:5000
          predicates:
            - Path=/weather/**

        - id: currency-service
          uri: http://localhost:5000
          predicates:
            - Path=/currency/**

        - id: auth-service
          uri: http://localhost:4000
          predicates:
            - Path=/auth/**

        # --- RUTAS PARA ROBAR LA DOCUMENTACIÓN (SWAGGER) ---
        - id: openapi-apis
          uri: http://localhost:5000
          predicates:
            - Path=/v3/api-docs/apis
          filters:
            - RewritePath=/v3/api-docs/apis, /v3/api-docs

        - id: openapi-auth
          uri: http://localhost:4000
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

# 🔥 CONFIGURACIÓN DEL SWAGGER CENTRAL 🔥
springdoc:
  swagger-ui:
    urls:
      - name: API Service (Weather & Currency)
        url: /v3/api-docs/apis
      - name: Auth Service
        url: /v3/api-docs/auth

# 🔥 "ESCÁNER" LOCAL DEL GATEWAY (Validación de tokens)
jwt:
  secret: my-super-secret-key-12345678901234567890